{
  "hash": "26eae4b4e7eea9e4336c3940f6aa9505",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Applied Visual Analytics on Motor Vehicle Insurance Portfolio Techical Report\"\nauthor: \"ZHANG Xiaoyu\"\ndate: \"May 16, 2026\"\ndate-modified: \"May 23,2026\"\nformat: html\ncode-link: true\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n# 1. Introduction & Project Setting\n\nIn the insurance industry, underperforming portfolios are often difficult to understand because the real causes of losses and volatility can remain hidden. Traditional business intelligence tools such as [Tableau]{.underline} and [Microsoft Power BI]{.underline} are useful for dashboard reporting, but they are mainly designed for static monitoring and offer limited support for deeper statistical exploration.\n\nThis technical report introduces a visual analytics sandbox built with R and `ggplot2` extensions to support more flexible and detailed analysis. The study uses a real-world dataset containing 354,140 automobile insurance policy transactions from a Spanish insurer between January 2022 and December 2024.\n\n![](motor%20insurance.jpg){fig-align=\"center\"}\n\nBy applying a range of univariate, bivariate, and multivariate visualization techniques, the report explores the key factors affecting portfolio profitability and volatility, with the goal of supporting more informed underwriting decisions.\n\n# 2. Analytical Sandbox & Data Wrangling\n\nTo build a reliable foundation for the analysis, we first import the raw dataset, clean and standardize the data types, remove records that may distort the actuarial analysis, and create several key insurance metrics for later exploration.\n\nFirst we will load the R packages using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(ggdist, ggstatsplot,\n               GGally, heatmaply,treemapify,\n               tidyverse) \n```\n:::\n\n\n-   **tidyverse**: An essential collection of packages designed for data science, used for data manipulation, cleaning, and core visualization (ggplot2).\n\n-   **ggdist**: Specialized for visualizing distributions and uncertainty, offering advanced geoms like raincloud plots.\n\n-   **ggstatsplot**: Automatically adds statistical test results and details directly onto `ggplot2` charts.\n\n-   **GGally**: Extends `ggplot2` by adding functions to easily plot correlation matrices, pairs plots, and networks.\n\n-   **heatmaply**: Used for creating interactive cluster heatmaps that allow users to zoom and hover for details.\n\n-   **treemapify**: Provides geoms to create treemaps within the `ggplot2` framework, useful for showing hierarchical structure.\n\n## 2.1 Data Import\n\nThe raw data is stored in CSV format, and we use `read.delim()` to import it while specifying the separator as a semicolon.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw_data <- read_delim(\"data/Dataset of motor insurance portfolio.csv\", delim = \";\")\n```\n:::\n\n\n### **Portfolio Overview**\n\nWe can see that the dataset contains anonymized motor vehicle insurance microdata from a Spanish insurance company. It spans from January 2022 to December 2024 and comprises **354,140 rows (records)** and **47 columns (variables)**.\n\n-   **Granularity**: Each row corresponds to an individual policy transaction rather than a unique static customer.\n\n-   **Key Identifier**: The `insured_id` variable represents individual policyholders. Multiple rows sharing the same `insured_id` indicate sequential transactions or renewals for the same customer over time.\n\n### Variable Classifications\n\n|  |  |  |\n|----|----|----|\n| **Variable Group** | **Description** | **Key Attributes Included** |\n| Policy and Insured Characteristics | Basic contractual definitions and historical account information. | `insured_id`, `policy_type`, `policy_status`, `business_type`, `bonus_score` |\n| Driver and Vehicle Characteristics | Risk profiles tied directly to the physical asset and operator demographics. | `driver_age`, `vehicle_age`, `age_driving_licence`, `fuel_type`, `vehicle_value`, `circulation_area` |\n| Premiums | Financial components detailing total and coverage-specific pricing allocations. | `total_premium`, `liability_premium`, `property_damage_premium`, `theft_premium` |\n| Exposure, Claims and Incurred | Operational outcomes measuring time-on-risk, claim events, and financial losses. | `total_exposure`, `total_claims`, `total_incurred`, `liability_incurred`, `property_incurred` |\n\n## 2.2 Data Cleaning and Feature Engineering\n\nActuarial Filtering: Policies must have positive risk exposure to calculate valid rates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_processed <- filter(raw_data, total_exposure > 0)\n```\n:::\n\n\nImpute Missing Values: Handle vehicle_value using median imputation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_processed <- mutate(insurance_processed, vehicle_value = as.numeric(vehicle_value))\nv_median <- median(insurance_processed$vehicle_value, na.rm = TRUE)\ninsurance_processed <- mutate(insurance_processed, vehicle_value = ifelse(is.na(vehicle_value), v_median, vehicle_value))\n```\n:::\n\n\nIn the next step, six core categorical attributes (\\`policy_type\\`, \\`fuel_type\\`, \\`municipality_type\\`, \\`circulation_area\\`, \\`business_type\\`, and \\`bonus_score\\`) are converted from raw text strings into R Factors to ensure to reorder chart elements based on frequency or logical business order instead of arbitrary alphabetical defaults.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_processed <- mutate(insurance_processed,\n  policy_type = as.factor(policy_type),\n  fuel_type = as.factor(fuel_type),\n  municipality_type = as.factor(municipality_type),\n  circulation_area = as.factor(circulation_area),\n  business_type = as.factor(business_type),\n  bonus_score = as.factor(bonus_score)\n)\n```\n:::\n\n\nNext,raw operational counters are transformed into relative rates and ratios to quantify portfolio performance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_processed <- mutate(insurance_processed,\n  earned_premium = total_premium * total_exposure,\n  loss_ratio = if_else(earned_premium > 0, total_incurred / earned_premium, 0.0),\n  claim_frequency = total_claims / total_exposure,\n  claim_severity = if_else(total_claims > 0, total_incurred / total_claims, 0.0)\n)\n```\n:::\n\n\nActuarial Binning of Continuous Demographics for Visual Segmentations\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_processed <- mutate(insurance_processed,\n  age_group = case_when(\n    driver_age < 25 ~ \"18-24 (Young)\",\n    driver_age >= 25 & driver_age < 45 ~ \"25-44 (Mid)\",\n    driver_age >= 45 & driver_age < 65 ~ \"45-64 (Senior)\",\n    driver_age >= 65 ~ \"65+ (Elderly)\"\n  ),\n  age_group = fct_relevel(age_group, \"18-24 (Young)\", \"25-44 (Mid)\", \"45-64 (Senior)\", \"65+ (Elderly)\")\n)\n```\n:::\n\n\nVerify the final cleaned sandbox dimensions,now the insurance_processed data has 354,091 rows and 52 columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(insurance_processed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 354,091\nColumns: 52\n$ insured_id                  <dbl> 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, …\n$ year                        <dbl> 2022, 2022, 2023, 2024, 2022, 2023, 2024, …\n$ policy_type                 <fct> COMP_E, COMP_E, COMP_E, COMP_E, COMP_E, CO…\n$ policy_status               <chr> \"C\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A\", \"A…\n$ business_type               <fct> NB, P, P, P, NB, P, P, NB, P, P, NB, P, P,…\n$ payment_frequency           <chr> \"A\", \"A\", \"A\", \"A\", \"S\", \"S\", \"S\", \"A\", \"A…\n$ bonus_score                 <fct> G, G, G, G, G, G, G, G, G, G, G, G, G, G, …\n$ driver_age                  <dbl> 48, 43, 44, 45, 45, 46, 47, 32, 33, 34, 39…\n$ vehicle_age                 <dbl> 22, 24, 25, 26, 26, 27, 28, 12, 13, 14, 20…\n$ age_driving_licence         <dbl> 26, 19, 19, 18, 19, 19, 19, 19, 19, 19, 19…\n$ fuel_type                   <fct> G, D, D, D, D, D, D, D, D, D, D, D, D, D, …\n$ vehicle_value               <dbl> 149511.44, 65065.12, 65065.12, 65065.12, 5…\n$ seats                       <dbl> 4, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, …\n$ power_to_weight_ratio       <dbl> 3.92, 10.15, 10.15, 10.15, 9.19, 9.19, 9.1…\n$ vehicle_brand               <chr> \"PORSCHE\", \"MERCEDES\", \"MERCEDES\", \"MERCED…\n$ municipality_type           <fct> I, I, I, I, I, I, I, I, I, I, C, I, I, C, …\n$ circulation_area            <fct> U, U, U, U, R, R, R, R, R, R, R, U, U, R, …\n$ total_premium               <dbl> 279.5576, 546.6234, 548.7526, 584.6324, 68…\n$ liability_premium           <dbl> 30.60232, 114.33336, 110.66689, 122.09253,…\n$ property_damage_premium     <dbl> 121.9127, 303.1060, 304.9560, 305.2251, 35…\n$ theft_premium               <dbl> 112.361489, 80.784824, 83.521384, 107.8868…\n$ fire_premium                <dbl> 3.832441, 7.826861, 6.151465, 5.842892, 7.…\n$ glass_premium               <dbl> 8.305788, 30.091751, 32.861626, 31.101584,…\n$ legal_protection_premium    <dbl> 2.043622, 7.812747, 7.655637, 10.084173, 6…\n$ occupants_premium           <dbl> 0.4992053, 2.6679084, 2.9395659, 2.3992827…\n$ total_claims                <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ liability_claims            <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_property_claims   <dbl> 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ liability_injury_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ property_claims             <dbl> 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ theft_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_claims                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_claims                <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_claims     <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_claims            <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_incurred              <dbl> 0.000, 0.000, 233.013, 2586.361, 0.000, 0.…\n$ liability_incurred          <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_property_incurred <dbl> 0.000, 0.000, 233.013, 1035.000, 0.000, 0.…\n$ liability_injury_incurred   <dbl> 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, …\n$ property_incurred           <dbl> 0.000, 0.000, 0.000, 1551.361, 0.000, 0.00…\n$ theft_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ fire_incurred               <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ glass_incurred              <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ legal_protection_incurred   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ occupants_incurred          <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ total_exposure              <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ liability_exposure          <dbl> 0.09863014, 1.00000000, 1.00000000, 1.0000…\n$ earned_premium              <dbl> 27.5728, 546.6234, 548.7526, 584.6324, 687…\n$ loss_ratio                  <dbl> 0.0000000, 0.0000000, 0.4246231, 4.4239104…\n$ claim_frequency             <dbl> 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, …\n$ claim_severity              <dbl> 0.0000, 0.0000, 233.0130, 1293.1807, 0.000…\n$ age_group                   <fct> 45-64 (Senior), 25-44 (Mid), 25-44 (Mid), …\n```\n\n\n:::\n:::\n\n\n# 3. Univariate Visual Analytics\n\nIt is important to start with univariate visual analysis, where each variable is examined on its own. This helps us understand the distribution of the data, spot any skewness in financial variables, and detect gaps or sparsity in certain operational segments.\n\nIt also ensures that the overall structure of the portfolio is consistent with basic actuarial assumptions before moving on to more complex multivariate analysis.\n\n## 3.1 Policy Type Distribution\n\nTo check the market share of each policy type across the company's business. We want to know which product is the most popular and understand the overall composition of our portfolio.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = insurance_processed, aes(x = fct_infreq(policy_type), fill = policy_type)) +\n  geom_bar(alpha = 0.8, show.legend = FALSE) +\n  geom_text(stat = 'count', aes(label = after_stat(count)), vjust = -0.5, size = 3.5) +\n  labs(\n    title = \"Distribution of Policy Types across the Portfolio\",\n    subtitle = \"Comparison of Third-Party vs Comprehensive Market Shares\",\n    x = \"Policy Type\",\n    y = \"Transaction Count\"\n  ) +\n  theme_minimal() +\n  scale_fill_brewer(palette = \"Purples\", direction = -1)\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-9-1.png){width=1344}\n:::\n:::\n\n\nThis bar chart shows the distribution of different policy types across our business portfolio:\n\n-   **CC**: This is the most common policy type, leading significantly with **204,609** transactions(**57.8%**).\n\n-   **COMP_E**: The second largest category, accounting for **91,186** transactions(**25.8%**).\n\n-   **TPG**: Positioned in the middle with **36,358** transactions(**10.3%**).\n\n-   **COMP_N**: A smaller segment representing **16,181** transactions(**4.6%**).\n\n-   **TP**: The least common policy type, with only **5,757** transactions(**1.6%**).\n\n## 3.2 Business Type Distribution (New Business vs. Renewal)\n\nThis step is to inspect the conversion health of our portfolio. We want to see whether our revenue is driven by acquiring new clients (New Business) or retaining existing accounts (Portfolio/Renewal), which directly affects long-term stability.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbusiness_summary <- count(insurance_processed, business_type)\nbusiness_summary <- mutate(business_summary,\n                           percentage = n / sum(n),\n                           label_text = paste0(scales::comma(n), \" (\", round(percentage * 100, 1), \"%)\"))\n\nggplot(data = business_summary, aes(x = business_type, y = n, fill = business_type)) +\n  geom_bar(stat = \"identity\", alpha = 0.8, show.legend = FALSE) +\n  geom_text(aes(label = label_text), vjust = -0.5, size = 4, fontface = \"bold\") +\n  scale_y_continuous(labels = scales::comma, limits = c(0, max(business_summary$n) * 1.15)) +\n  labs(\n    title = \"Business Type\",\n    subtitle = \"Comparing volumes of new business (NB) vs. portfolio (P)\",\n    x = \"Business Type\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal() +\n  scale_fill_manual(values = c(\"NB\" = \"#6A4C93\", \"P\" = \"#D6C7E8\"))\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThe chart suggests that the portfolio is growing aggressively and relies heavily on new customer acquisition.\n\n-   Nearly 70% of the total risk exposure comes from brand-new clients, showing that the business depends more on attracting new policyholders than retaining existing ones.\n\n-   From a risk management perspective, this may increase uncertainty because new customers are generally less predictable than long-term renewal clients.\n\n-   In contrast, renewal policies are usually more stable and easier to assess based on historical experience.\n\n## 3.3 Annual Premium Revenue Evolution\n\nThis step is to track the total cash inflow of incoming business over the calendar years. Based on exploratory of raw data, we assume that \\`total_premium\\` represents the absolute realized financial revenue collected for each transaction, requiring no fractional exposure-based discounting (total_premium = revenue).\n\n\n::: {.cell}\n\n```{.r .cell-code}\npremium_annual <- group_by(insurance_processed, year)\npremium_annual <- summarize(premium_annual, total_premium_sum = sum(total_premium, na.rm = TRUE))\n\npremium_annual <- mutate(premium_annual,\n  label_text = paste0(\"$\", scales::comma(total_premium_sum))\n)\n\nggplot(data = premium_annual, aes(x = as.factor(year), y = total_premium_sum, fill = total_premium_sum)) +\n  geom_bar(stat = \"identity\", alpha = 0.85, show.legend = FALSE, width = 0.5) +\n  geom_text(aes(label = label_text), vjust = -0.4, size = 3.8, fontface = \"bold\") +\n  scale_y_continuous(labels = scales::comma, limits = c(0, max(premium_annual$total_premium_sum) * 1.2)) +\n  labs(\n    title = \"Annual Realized Premium\",\n    x = \"Accounting Year\",\n    y = NULL\n  ) +\n  theme_minimal() +\n  scale_fill_gradient(low = \"#ce93d8\", high = \"#6a1b9a\") +\n  theme(\n    panel.grid.major.x = element_blank(),\n    axis.text.x = element_text(size = 10, fontface = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nThis bar chart illustrates the growth trend of **Annual Realized Premium** over a three-year period from 2022 to 2024.\n\n-   **2022**: The portfolio generated **\\$18,697,928** in realized premiums.\n\n-   **2023**: Premium volume rose significantly to **\\$35,344,308**, representing an approximate **89% increase** year-over-year.\n\n-   **2024**: The growth continued strongly, peaking at **\\$51,037,433**, which is an additional **44% increase** from 2023.\n\nThe chart reflects an **explosive and aggressive revenue expansion**. In just two years, the annual realized premium has nearly tripled (growing from \\~\\$18.7M to \\~\\$51M).\n\n## 3.4 Annual Incurred Claims\n\nThis step is to monitor the volume of financial losses paid out over the calendar years.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclaims_amount_annual <- group_by(insurance_processed, year)\nclaims_amount_annual <- summarize(claims_amount_annual, total_claims_sum = sum(total_incurred, na.rm = TRUE))\n\n\nclaims_amount_annual <- mutate(claims_amount_annual,\n  label_text = paste0(\"$\", scales::comma(total_claims_sum))\n)\n\n\nggplot(data = claims_amount_annual, aes(x = as.factor(year), y = total_claims_sum, fill = total_claims_sum)) +\n  geom_bar(stat = \"identity\", alpha = 0.85, show.legend = FALSE, width = 0.5) +\n  geom_text(aes(label = label_text), vjust = -0.4, size = 3.8, fontface = \"bold\") +\n  scale_y_continuous(labels = scales::comma, limits = c(0, max(claims_amount_annual$total_claims_sum) * 1.2)) +\n  labs(\n    title = \"Annual Incurred Claims\",\n    x = NULL,\n    y = NULL\n  ) +\n  theme_minimal() +\n  scale_fill_gradient(low = \"#b39ddb\", high = \"#4527a0\") +\n  theme(\n    panel.grid.major.x = element_blank(),\n    axis.text.x = element_text(size = 10, fontface = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThis bar chart tracks the growth of **Annual Incurred Claims** from 2022 to 2024.\n\n-   **2022**: Total incurred claims stood at **\\$12,269,925**.\n\n-   **2023**: Costs rose significantly to **\\$23,488,354** (a **91.4% increase** year-over-year).\n\n-   **2024**: Claim financial exposure peaked at **\\$38,106,351**, marking an additional **62.2% increase** from 2023.\n\n## 3.5 Annual Average Claim Severity\n\nThis step is to track the average financial cost of a single claim over the calendar years. By dividing total incurred losses by the number of claims, we can see if individual accident costs are rising or stabilizing, which helps separate high-frequency trends from severe, costly individual events.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nseverity_annual <- group_by(insurance_processed, year)\nseverity_annual <- summarize(severity_annual,\n  avg_severity = sum(total_incurred, na.rm = TRUE) / sum(total_claims, na.rm = TRUE)\n)\n\nseverity_annual <- mutate(severity_annual,\n  label_text = paste0(\"$\", scales::comma(round(avg_severity, 0)))\n)\n\nggplot(data = severity_annual, aes(x = as.factor(year), y = avg_severity, fill = avg_severity)) +\n  geom_bar(stat = \"identity\", alpha = 0.85, show.legend = FALSE, width = 0.5) +\n  geom_text(aes(label = label_text), vjust = -0.4, size = 3.8, fontface = \"bold\") +\n  scale_y_continuous(labels = scales::comma, limits = c(0, max(severity_annual$avg_severity) * 1.2)) +\n  labs(\n    title = \"Annual Average Claim Severity Trend\",\n    x = NULL,\n    y = NULL\n  ) +\n  theme_minimal() +\n  scale_fill_gradient(low = \"#b39ddb\", high = \"#4527a0\") +\n  theme(\n    panel.grid.major.x = element_blank(),\n    axis.text.x = element_text(size = 10, fontface = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n**This chart shows that the average cost of an individual claim has remained remarkably stable (fluctuating by less than 4% around the \\$950 mark)** over the three years.\n\nConnecting this with the previous charts leads to a vital strategic conclusion: The massive surge in total claim costs (which jumped from \\$12.3M to \\$38.1M) is **not** driven by inflation or claims becoming more expensive individually. Instead, it is driven entirely by the sheer volume of claims. Our risk management team should focus on controlling the number of accidents rather than the cost per accident.\n\n## 3.6 Policyholder Credit Rating\n\nThis step is to review the quality of our policyholders. This tells us whether our client base consists mostly of low-risk safe drivers or high-risk drivers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbonus_summary <- count(insurance_processed, bonus_score)\nbonus_summary <- mutate(bonus_summary, \n                        percentage = n / sum(n),\n                        label_text = paste0(round(percentage * 100, 1), \"%\"))\n\nggplot(data = bonus_summary, aes(x = percentage, y = reorder(bonus_score, percentage), fill = bonus_score)) +\n  geom_bar(stat = \"identity\", alpha = 0.8, show.legend = FALSE) +\n  geom_text(aes(label = label_text), hjust = -0.2, size = 4, fontface = \"bold\") +\n  scale_x_continuous(labels = scales::percent, limits = c(0, max(bonus_summary$percentage) * 1.15)) +\n  labs(\n    title = \"Policyholder Credit Rating\",\n    subtitle = \"Proportional of portfolio client quality (G: Good, N: Neutral, B: Bad)\",\n    x = \"Percentage\",\n    y = \"Bonus Score Rating\"\n  ) +\n  theme_minimal() +\n  scale_fill_brewer(palette = \"Set2\")\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nThis bar chart shows the distribution of policyholder credit ratings across the portfolio, categorized into three levels: **G** (Good), **N** (Neutral), and **B** (Bad).\n\n-   **G (Good)**: This is the dominant category, accounting for the vast majority of the portfolio at **96.4%**.\n\n-   **N (Neutral)**: A very small segment, representing only **2.2%** of the total.\n\n-   **B (Bad)**: The smallest group, making up just **1.3%** of the portfolio.\n\nThis means the portfolio's client quality is highly concentrated in the \"Good\" rating, with minimal exposure to \"Neutral\" or \"Bad\" credit risks.\n\n## 3.7 **Active Insurance Period**\n\nThis step is to check how long policies actually stay active on risk. We want to see whether our dataset is dominated by full-year standard contracts (exposure close to 1.0) or short-term canceled/mid-term policies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_processed <- mutate(insurance_processed,\n  exposure_group = case_when(\n    total_exposure < 0.5 ~ \"Short-term (<0.5 Yr)\",\n    total_exposure >= 0.5 & total_exposure < 1.0 ~ \"Mid-term (0.5 - <1 Yr)\",\n    total_exposure == 1.0 ~ \"Full Year (Exactly 1 Yr)\",\n    total_exposure > 1.0 ~ \"Long-term (>1 Yr)\"\n  )\n)\n\nexposure_summary <- count(insurance_processed, exposure_group)\nexposure_summary <- mutate(exposure_summary,\n  percentage = n / sum(n),\n  label_text = paste0(scales::comma(n), \" (\", round(percentage * 100, 1), \"%)\"),\n  exposure_group = fct_relevel(exposure_group, \n                               \"Short-term (<0.5 Yr)\", \n                               \"Mid-term (0.5 - <1 Yr)\", \n                               \"Full Year (Exactly 1 Yr)\", \n                               \"Long-term (>1 Yr)\")\n)\n\nggplot(data = exposure_summary, aes(x = exposure_group, y = n, fill = exposure_group)) +\n  geom_bar(stat = \"identity\", alpha = 0.8, show.legend = FALSE) +\n  geom_text(aes(label = label_text), vjust = -0.5, size = 3.5, fontface = \"bold\") +\n  scale_y_continuous(labels = scales::comma, limits = c(0, max(exposure_summary$n) * 1.15)) +\n  labs(\n    title = \"Active Insurance Period\",\n    x = \"Active Insurance Period\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal() +\n  scale_fill_brewer(palette =\"Purples\" , direction = -1)\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nThis chart addresses our earlier concern about contract stability. While full-year contracts represent the largest share (40%), **the remaining 60% of the dataset consists of short-term or mid-term policies**.\n\nThis indicates a high volume of mid-term cancellations, early lapses, or temporary coverages within the portfolio. From an analytical standpoint, this confirms that we cannot treat all policies equally; we must use the actual exposure values to weight our risk and pricing models, as a large portion of the clients were not covered for the full year.\n\n## 3.8 Vehicle Value Distribution Shape\n\nThis step is to examine the cost profile of the insured vehicles. We want to see if the values are heavily skewed, which helps underwriters understand our potential maximum exposure to expensive total-loss claims.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = insurance_processed, aes(x = \"\", y = vehicle_value)) +\n  geom_violin(fill = \"#D6C7E8\", color = \"black\", alpha = 0.8, width = 0.6) +\n  geom_boxplot(width = 0.3, fill = \"white\", color = \"black\", \n               outlier.size = 1, outlier.color = \"dimgray\") +\n  stat_summary(fun = mean, geom = \"point\", color = \"red\", size = 3) +\n  scale_y_continuous(labels = scales::comma,\n                     breaks = seq(0, 400000, by = 50000)\n                     ) +\n  \n  labs(\n    title = \"Vehicle Value Distribution\",\n    subtitle = \"Boxplot revealing the mean and distribution\",\n    x = NULL,\n    y = \"Vehicle Value\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_blank(),           \n    panel.grid.major.x = element_blank(),   \n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nFrom this chart we can see that while most insured vehicles are of low value, the few high-value outliers represent a potential source of high-severity volatility in claims.\n\n-   **The Wide Bottom (High Density)**: The widest part of the violin plot is at the very bottom, meaning the vast majority of vehicles are highly concentrated in the lower price range, mostly below **\\$50,000**.\n\n-   **The Flat Boxplot**: Because the data is so heavily compressed at the bottom, the white box (which shows the quartiles) is very thin and sits near the baseline.\n\n-   **The Long Tail (Outliers)**: The plot stretches upward into a very thin line filled with grey dots. This represents a long right-skewed tail, showing that a few rare vehicles have exceptionally high values, reaching up to **\\$380,000**.\n\n-   **The Red Dot (Mean)**: The red dot represents the average vehicle value. Because it is pulled upward by the few extremely expensive vehicles, the average is noticeably higher than the median (the black line inside the box).\n\n## 3.9 Vehicle Power-to-Weight Ratio Distribution\n\nThis step is to check the performance levels of the insured vehicles. High outliers point to sports cars or high-performance models, allowing us to see if we are insuring too many aggressive, heavy-risk vehicles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = insurance_processed, aes(x = \"\", y = power_to_weight_ratio)) +\n  geom_violin(fill = \"#D6C7E8\", color = \"black\", alpha = 0.8, width = 0.6, adjust=2) +\n  \n  geom_boxplot(width = 0.3, fill = \"white\", color = \"black\", \n               outlier.size = 1, outlier.color = \"dimgray\") +\n  \n  stat_summary(fun = mean, geom = \"point\", color = \"red\", size = 3) +\n  \n  labs(\n    title = \"Power-to-Weight Ratio\",\n    subtitle = \"Boxplot revealing the mean and distribution\",\n    x = NULL,\n    y = \"Power-to-Weight Ratio (kg per horsepower)\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_blank(),           \n    panel.grid.major.x = element_blank(),     \n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nThis chart shows that the portfolio's vehicle performance risk is highly uniform, with only a small number of extreme outliers deviating from the standard passenger model.\n\n-   **The Wide Center (High Density)**: The widest part of the violin plot is heavily concentrated at the bottom, specifically between **10 and 15 kg per horsepower**. This indicates that the vast majority of vehicles in the portfolio fall into this standard performance range.\n\n-   **The Compressed Boxplot**: The white box representing the middle 50% of the data is quite narrow and sits entirely within this lower high-density zone, showing low variation among standard vehicles.\n\n-   **The Long Upper Tail (Outliers)**: The plot extends into a very tall, thin vertical line reaching up to over **60 kg per horsepower**, marked by numerous grey dots. These outliers represent a small segment of vehicles with unusual performance specifications.\n\n-   **The Red Dot (Mean)**: The red dot marks the average power-to-weight ratio. It is located very close to the median (the black line inside the box), indicating that despite the long tail of outliers, the sheer volume of data concentrated at the bottom keeps the portfolio's overall average stable.\n\n## 3.10 Vehicle Age Distribution (New vs. Old Cars)\n\nThis step is to examine the physical age profile of the insured vehicle. Understanding whether our portfolio is dominated by brand-new vehicles or older cars helps underwriters assess baseline mechanical risk and depreciation patterns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_processed <- mutate(insurance_processed,\n  vehicle_age_binned = case_when(\n    vehicle_age >= 0  & vehicle_age < 10 ~ \"0-10\",\n    vehicle_age >= 10 & vehicle_age < 20 ~ \"10-20\",\n    vehicle_age >= 20 & vehicle_age < 30 ~ \"20-30\",\n    vehicle_age >= 30 & vehicle_age < 40 ~ \"30-40\",\n    vehicle_age >= 40 & vehicle_age < 50 ~ \"40-50\",\n    vehicle_age >= 50                    ~ \"50+(Extreme Old)\"\n  )\n)\n\n\nvehicle_age_summary <- count(insurance_processed, vehicle_age_binned)\nvehicle_age_summary <- filter(vehicle_age_summary, !is.na(vehicle_age_binned)) \n\nvehicle_age_summary <- mutate(vehicle_age_summary,\n  percentage = n / sum(n),\n  label_text = paste0(scales::comma(n), \"\\n(\", round(percentage * 100, 1), \"%)\"),\n  vehicle_age_binned = fct_relevel(vehicle_age_binned, \n                                   \"0-10\", \"10-20\", \"20-30\", \n                                   \"30-40\", \"40-50\", \"50+ (Extreme Old)\")\n)\n\nggplot(data = vehicle_age_summary, aes(x = vehicle_age_binned, y = n, fill = n)) +\n  geom_bar(stat = \"identity\", alpha = 0.85, show.legend = FALSE) +\n  geom_text(aes(label = label_text), vjust = -0.2, size = 3.5, fontface = \"bold\", lineheight = 0.9) +\n  scale_y_continuous(labels = scales::comma, limits = c(0, max(vehicle_age_summary$n) * 1.2)) +\n  labs(\n    title = \"Insured Vehicle Age Distribution\",\n    x = \"Vehicle Age\",\n    y = \"Number of Policies\"\n  ) +\n  theme_minimal() +\n  scale_fill_gradient(low = \"#d1c4e9\", high = \"#4a148c\") +\n  theme(\n    panel.grid.major.x = element_blank(),\n    axis.text.x = element_text(angle = 0, vjust = 1, hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nFrom this chart we can see that the portfolio carries a distinctive **aging vehicle risk**. Having nearly 70% of insured vehicles older than 20 years (and more than 30% older than 30 years) suggests that the business primarily covers older models.\n\nIn insurance underwriting, older vehicles generally have lower market values but might face different risk profiles, such as higher mechanical failure rates or scarcity of replacement parts during claims.\n\n## 3.11 Insured Vehicle Seats Capacity\n\nThis step is to evaluate the vehicle capacity risk across our business. We want to discover if the majority of cars are standard 5-seaters or if there are large commercial passenger vans/buses, which bring higher human-injury risk per accident.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Group continuous seat counts into logical underwriting risk cohorts\ninsurance_processed <- mutate(insurance_processed,\n  seats_group = case_when(\n    seats < 5  ~ \"Less than 5 Seats\",\n    seats == 5 ~ \"Exactly 5 Seats\",\n    seats > 5  ~ \"More than 5 Seats (>5)\"\n  )\n)\n\n# Step 2: Pre-aggregate the data to calculate clean counts and percentages\nseats_summary <- count(insurance_processed, seats_group)\nseats_summary <- filter(seats_summary, !is.na(seats_group)) \n\nseats_summary <- mutate(seats_summary,\n                        percentage = n / sum(n),\n                        label_text = paste0(scales::comma(n), \" (\", round(percentage * 100, 1), \"%)\"),\n                        seats_group = fct_relevel(seats_group, \n                                                  \"Less than 5 Seats\", \n                                                  \"Exactly 5 Seats\", \n                                                  \"More than 5 Seats (>5)\"))\n\n# Step 3: Plot the clean horizontal grouped bar chart with a purple gradient\nggplot(data = seats_summary, aes(x = n, y = seats_group, fill = n)) +\n  geom_bar(stat = \"identity\", alpha = 0.85, show.legend = FALSE) +\n  geom_text(aes(label = label_text), hjust = -0.05, size = 3, fontface = \"bold\") +\n  scale_x_continuous(labels = scales::comma, limits = c(0, max(seats_summary$n) * 1.25)) +\n  labs(\n    title = \"Vehicle Seats Capacity Distribution\",\n    x = \"Number of Policies\",\n    y = NULL\n  ) +\n  theme_minimal() +\n  scale_fill_gradient(low = \"#e1bee7\", high = \"#4a148c\") +\n  theme(\n    panel.grid.major.y = element_blank(),\n    axis.text.y = element_text(size = 10, fontface = \"bold\") \n  )\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nThis bar chart displays the distribution of **Vehicle Seats Capacity** within the insurance portfolio, grouped into three categories based on the number of seats.\n\n-   **Overwhelming Dominance (Exactly 5 Seats)**: The dark purple bar shows that **300,669** policies are for vehicles with exactly 5 seats. This represents the vast majority (**84.9%**) of the entire portfolio.\n\n-   **Larger Vehicles (More than 5 Seats)**: Vehicles with a higher seating capacity (such as 7-seater SUVs or minivans) account for **30,453** policies, making up **8.6%** of the total.\n\n-   **Smaller Vehicles (Less than 5 Seats)**: Two-seater sports cars or small city cars are the smallest segment, with **22,969** policies (**6.5%**).\n\nThe chart indicates that the portfolio has an extremely high concentration of **standard 5-seater passenger cars**.It represents a typical private passenger car market, with very low exposure to specialized smaller cars or larger multi-purpose/commercial passenger vehicles.\n\n## 3.12 Driver Age Demographics by Area (Faceting)\n\nThis step is to learn how driver ages are distributed between urban and rural areas. This shows us if certain environments have a higher concentration of unexperienced young drivers or older operators.\n\nBefore analyzing the age demographics, it is important to understand the overall distribution of policies across geographic zones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\narea_summary <- count(insurance_processed, circulation_area)\narea_summary <- mutate(area_summary,\n                       percentage = n / sum(n),\n                       label_text = paste0(\"Total Policies: \", scales::comma(n), \n                                           \" (\", round(percentage * 100, 1), \"%)\"))\nprint(area_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  circulation_area      n percentage label_text                     \n  <fct>             <int>      <dbl> <chr>                          \n1 R                163607      0.462 Total Policies: 163,607 (46.2%)\n2 U                190484      0.538 Total Policies: 190,484 (53.8%)\n```\n\n\n:::\n:::\n\n\nThe portfolio shows a higher concentration of clients in urban areas.\n\n-   **Urban (U)**: Accounts for **190,484** policies, representing **53.8%** of the total portfolio.\n\n-   **Rural (R)**: Accounts for **163,607** policies, representing **46.2%** of the total portfolio.\n\n*(Total volume: 354,091 policies)*\n\nThen we use histogram to display the distribution of driver ages across urban and rural zones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_range <- range(insurance_processed$driver_age, na.rm = TRUE)\nbin_width <- (age_range[2] - age_range[1]) / 30\nggplot(data = insurance_processed, aes(x = driver_age)) +\n  geom_histogram(bins = 30, fill = \"#6A4C93\", color = \"white\", alpha = 0.7) +\n  geom_density(aes(y = after_stat(density) * nrow(insurance_processed) / 2 * bin_width), \n               adjust = 2.5,\n               color = \"#FFB703\", \n               linewidth = 1) +\n  \n  facet_wrap(~ circulation_area, labeller = as_labeller(c(\"U\" = \"Urban\", \"R\" = \"Rural\"))) +\n  labs(\n    title = \"Driver Age Distribution with Smooth Trend Lines\",\n    subtitle = \"Evaluating demographic differences across geographic risk zones\",\n    x = \"Driver Age\",\n    y = \"Count\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nThis chart demonstrates that despite the distinct geographic settings, the underlying **age demographics of the drivers are nearly identical** across both portfolio segments.\n\n-   **Similar Shape**: Both environments show a very similar age profile, the vast majority of drivers are concentrated between **35 and 55 years old**.\n\n-   **The Smooth Trend Lines**: The red curves filter out the minor fluctuations of individual bars to capture the overall demographic trend.\n\n    -   In the **Rural** plot, the curve peaks smoothly around age 40 and then gradually slopes down.\n\n    -   In the **Urban** plot, the curve shows a slightly broader plateau between ages 40 and 55, reflecting a slightly higher presence of middle-aged urban drivers.\n\n-   **Volume Difference**: The vertical bars in the **Urban** panel are generally taller (peaking near 16,000) than those in the **Rural** panel (peaking around 15,000), indicating a larger overall sample size of insured clients in city environments.\n\n# 4. Bivariate Visual Analytics & Statistical Validation\n\nWhile univariate analysis helps us understand each variable individually, it cannot show how different factors interact to affect portfolio performance. Bivariate visual analysis allows us to explore the relationships between two variables at a time, such as how driver characteristics or vehicle features are related to claim frequency and loss ratios.\n\nHowever, visual patterns alone are not always reliable because they can be influenced by random fluctuations or differences in sample size. To make the analysis more dependable for underwriting decisions, statistical tests such as correlation analysis and ANOVA are incorporated into the visualizations. These tests help confirm whether the observed differences are statistically meaningful or simply caused by chance.\n\n## 4.1 Driver Age & Claim Frequency\n\nThis step is to test if driver age has a statistically significant relationship with financial loss ratios. We want to confirm whether older drivers are truly more profitable than young ones using mathematical validation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_processed <- mutate(insurance_processed,\n  driver_age_group = case_when(\n    driver_age >= 18 & driver_age < 30 ~ \"20-29 Yrs\",\n    driver_age >= 30 & driver_age < 40 ~ \"30-39 Yrs\",\n    driver_age >= 40 & driver_age < 50 ~ \"40-49 Yrs\",\n    driver_age >= 50 & driver_age < 60 ~ \"50-59 Yrs\",\n    driver_age >= 60                   ~ \"60+ Yrs\"\n  )\n)\n\nfrequency_summary <- insurance_processed %>%\n  filter(total_claims > 0 & total_claims <= 5) %>% \n  group_by(driver_age_group, total_claims) %>%\n  summarize(policy_count = n(), .groups = \"drop\") %>%\n  group_by(driver_age_group) %>%\n  mutate(\n    percentage = policy_count / sum(policy_count),\n    label_text = paste0(scales::comma(policy_count), \"\\n(\", round(percentage * 100, 1), \"%)\"),\n    driver_age_group = fct_relevel(driver_age_group, \"20-29 Yrs\", \"30-39 Yrs\", \"40-49 Yrs\", \"50-59 Yrs\", \"60+ Yrs\")\n  ) %>%\n  filter(!is.na(driver_age_group))\n\nggplot(data = frequency_summary, aes(x = policy_count, y = as.factor(total_claims), fill = as.factor(total_claims))) +\n  geom_bar(stat = \"identity\", alpha = 0.85, show.legend = FALSE, width = 0.5) +\n  geom_text(aes(label = label_text), hjust = -0.08, size = 3, fontface = \"bold\", lineheight = 0.85) +\n  scale_x_continuous(labels = scales::comma, expand = expansion(mult = c(0, 0.45))) +\n  facet_wrap(~ driver_age_group, nrow = 1) + \n  labs(\n    title = \"Claim Frequency Distribution Across Driver Age Group\",\n    x = \"Number of Policies\",\n    y = \"Number of Claims Incurred\"\n  ) +\n  theme_minimal() +\n  scale_fill_brewer(palette = \"Purples\") + \n  theme(\n    panel.grid.major.y = element_blank(),\n    strip.background = element_rect(fill = \"#f3e5f5\", color = NA),\n    strip.text = element_text(size = 9, fontface = \"bold\", color = \"#4a148c\"), \n    axis.title.y = element_text(size = 9, fontface = \"bold\", color = \"gray30\"), \n    axis.text.y = element_text(size = 8.5, fontface = \"bold\"),\n    axis.text.x = element_text(size = 7.5) \n  )\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nThis chart provides a detailed look at the exact distribution of claim counts within each driver age group across the full dataset.\n\n-   **1 Claim**: In every single age group, approximately **70% to 72%** of policies incur exactly 1 claim.\n\n-   **2 Claims**: Consistently represents around **17% to 18%** of the policies across all brackets.\n\n-   **3 to 5 Claims**: The shares drop off at nearly the identical rate in every panel (around 6% to 8% for 3 claims, \\~3% for 4 claims, and \\~1.5% to 2% for 5 claims).\n\n-   **Volume Differences (The Counts)**: While the *proportions* are identical, the absolute number of policies (the actual counts) is much lower in the **20-29 Yrs** group compared to the mature groups, reflecting the portfolio's underlying age distribution.\n\nNext, we will use statistical testing methods to determine whether there are significant differences in the number of claims across the various age groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsurance_processed <- mutate(insurance_processed,\n  driver_age_group = case_when(\n    driver_age >= 18 & driver_age < 30 ~ \"20-29 Yrs\",\n    driver_age >= 30 & driver_age < 40 ~ \"30-39 Yrs\",\n    driver_age >= 40 & driver_age < 50 ~ \"40-49 Yrs\",\n    driver_age >= 50 & driver_age < 60 ~ \"50-59 Yrs\",\n    driver_age >= 60                   ~ \"60+ Yrs\"\n  )\n)\n\nclaims_density_subset <- filter(insurance_processed, total_claims > 0 & total_claims <= 10)\n\nset.seed(123)\nbi_sample <- sample_n(claims_density_subset, min(nrow(claims_density_subset), 1500))\n\nbi_sample$driver_age_group <- fct_relevel(bi_sample$driver_age_group, \n                                          \"20-29 Yrs\", \"30-39 Yrs\", \"40-49 Yrs\", \"50-59 Yrs\", \"60+ Yrs\")\n\nggbetweenstats(\n  data = bi_sample,\n  x = driver_age_group,\n  y = total_claims,\n  type = \"p\",       \n  mean.ci = TRUE,           \n  pairwise.comparisons = TRUE,\n  pairwise.display = \"s\", \n  p.adjust.method = \"fdr\", \n  messages = FALSE,         \n  title = \"Claim Frequency Distribution Across Driver Age Groups\",\n  xlab = \"Driver Age Cohort\",\n  ylab = \"Number of Incurred Claims (Frequency per Policy)\",\n  package = \"ggthemes\",\n  palette = \"Purple_Pink\"   \n)\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nInstead of using the entire dataset, a random sample of $n_{\\text{obs}} = 1,500$ policies was drawn for this analysis.\n\nBecause the sample sizes and variances across the groups are unequal, a robust **Welch's ANOVA** test was applied (shown at the top of the chart):\n\n-   **F-statistic**: $F_{\\text{Welch}}(4, 283.41) = 2.08$\n\n-   **p-value**: $p = 0.08$\n\nIn standard hypothesis testing, a significance threshold ($\\alpha$) of **0.05** is used.\n\n-   Since the **p-value (**0.08) is greater than $0.05$, the test fails to reject the null hypothesis.\n\n-   **Conclusion**: There is **no statistically significant difference** in the number of claims across the various driver age groups.\n\n## 4.2 Claims Severity Analysis across Vehicle Age\n\nThis step is to evaluate whether vehicle age exhibit statistically significant differences in claim severity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nassociation_data <- insurance_processed %>%\n  filter(total_incurred > 0 & !is.na(vehicle_age_binned)) %>%\n  mutate(\n    loss_severity_bins = case_when(\n      total_incurred > 0     & total_incurred <= 2000  ~ \"Low Loss (<$2K)\",\n      total_incurred > 2000  & total_incurred <= 10000 ~ \"Medium Loss ($2K-$10K)\",\n      total_incurred > 10000                           ~ \"High Loss (>$10K)\"\n    )\n  )\n\nassociation_data$vehicle_age_binned <- fct_relevel(association_data$vehicle_age_binned, \n                                                   \"New\", \"Moderate\", \"Old\")\nassociation_data$loss_severity_bins = fct_relevel(association_data$loss_severity_bins, \n                                                   \"Low Loss (<$2K)\", \"Medium Loss ($2K-$10K)\", \"High Loss (>$10K)\")\n\nggbarstats(\n  data = association_data,      \n  x = loss_severity_bins,       \n  y = vehicle_age_binned,     \n  bf.message = FALSE,           \n  labels.size = 3,            \n  title = \"Significant Test of Association: Active Loss Severity vs. Vehicle Age Brackets\",\n  xlab = \"Vehicle Age Group\",\n  legend.title = \"Loss Severity Brackets\",\n  package = \"ggthemes\",\n  palette = \"Purple_Pink\"       \n)\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-24-1.png){width=1344}\n:::\n:::\n\n\nLooking across all vehicle age groups (from brand new 0-10 years to extremely old 50+ years), the proportion of claim costs remains remarkably identical:\n\n-   **Low Loss (**$<\\$2\\text{K}$): Dominates the entire portfolio, consistently making up **78% to 82%** of claims in every single category.\n\n-   **Medium Loss (**$\\$2\\text{K}-\\$10\\text{K}$): Accounts for a steady **16% to 19%** of claims.\n\n-   **High Loss (**$>\\$10\\text{K}$): Remains rare, hovering at just **2% to 3%** across all age groups.\n\nWhile the p-value ($0.00954$) is below the standard $0.05$ threshold,this means there is a *statistically* difference,the correlation is extremely weak (only 1% association), making it practically negligible for actual insurance operations.\n\n## 4.3 Underwriting Performance across Product Types\n\nThis step is to compare the financial premium earning capacity across different insurance product types. Because premium revenue metrics are continuous and heavily right-skewed, we deploy a parametric **Welch's One-Way ANOVA** via `ggbetweenstats()` to test for revenue variations across commercial products.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npremium_dist_data <- insurance_processed %>%\n  filter(total_premium > 0 & !is.na(policy_type))\n\npremium_dist_data %>%\n  ggplot(aes(x = policy_type, y = total_premium, fill = policy_type, color = policy_type)) +\n  stat_gradientinterval(\n    fill = \"#8e24aa\",          \n    color = \"#4a148c\",          \n    .width = c(.66, .95),     \n    alpha = 0.75,\n    show.legend = FALSE\n  ) +\n\n  coord_cartesian(ylim = c(0, 2500)) + \n  labs(\n    title = \"Confidence Intervals & Uncertainty of Mean Premium\",\n    x = \"Insurance Product Types\",\n    y = \"Total Premium\"\n  ) +\n  theme_minimal() +\n  scale_y_continuous(labels = scales::dollar) + \n  theme(\n    panel.grid.major.x = element_blank(),        \n    axis.title.x = element_text(size = 9, fontface = \"bold\", color = \"gray30\"),\n    axis.title.y = element_text(size = 9, fontface = \"bold\", color = \"gray30\"),\n    axis.text.x = element_text(size = 9, fontface = \"bold\"),\n    axis.text.y = element_text(size = 8.5),\n    plot.title = element_text(size = 12, fontface = \"bold\"),\n    plot.subtitle = element_text(size = 9, color = \"gray40\")\n  )\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nThis chart visualizes the **Average Total Premium** and its associated **Confidence Intervals** across five different insurance product types (CC, COMP_E, COMP_N, TP, TPG).\n\n-   **COMP_N**: Has the **highest average premium** (around \\$600), but also exhibits the **most extreme uncertainty**. The line stretches drastically from nearly \\$0 to over \\$1,700, indicating that prices within this product are highly volatile or data is sparse.\n\n-   **COMP_E**: Has the second highest average premium (around \\$380) with moderate uncertainty.\n\n-   **CC, TPG, and TP**: These represent the lower priced, more stable products. **TP** has the **lowest average premium** (around \\$170). Their short vertical lines prove that their average pricing is highly consistent and predictable.\n\nWhile it is easy to understand that different products have different premium rates, from a business perspective, we are more interested in their profitability.\n\nNext, we will combine premium revenues with incurred claims to analyze the financial performance of each product.\n\n## 4.4 Profit Performance across Product Types\n\nThis step is to evaluate and compare the true financial profitability across different product types. Instead of analyzing raw premium volume, this section uses the **Loss Ratio** (Total Incurred Loss divided by Total Premium) as the core performance metric.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nportfolio_profitability <- insurance_processed %>%\n  filter(total_premium > 0 & !is.na(policy_type)) %>%\n  group_by(policy_type) %>%\n  summarize(\n    global_incurred = sum(total_incurred, na.rm = TRUE),\n    global_premium  = sum(total_premium, na.rm = TRUE),\n    portfolio_loss_ratio = global_incurred / global_premium,\n    .groups = \"drop\"\n  ) %>%\n  mutate(policy_type = fct_reorder(policy_type, portfolio_loss_ratio))\n\nggplot(data = portfolio_profitability, aes(x = policy_type, y = portfolio_loss_ratio, fill = portfolio_loss_ratio)) +\n\n  geom_bar(stat = \"identity\", width = 0.55, alpha = 0.85, show.legend = FALSE) +\n  geom_text(aes(label = scales::percent(portfolio_loss_ratio, accuracy = 0.1)), \n            hjust = -0.15, size = 3.5, fontface = \"bold\", color = \"gray20\") +\n  coord_flip() +\n  scale_y_continuous(labels = scales::percent, expand = expansion(mult = c(0, 0.15))) +\n  scale_fill_gradient(low = \"#e1bee7\", high = \"#4a148c\") +\n  labs(\n    title = \"Portfolio Loss Ratio Across Insurance Policy Types\",\n    subtitle = \"Calculated as (Sum of Incurred Losses / Sum of Premiums)\",\n    x = \"Policy Types\",\n    y = \"Loss Ratio (%)\"\n  ) +\n  theme_minimal() +\n  theme(\n    panel.grid.major.y = element_blank(),\n    axis.title.x = element_text(size = 9, fontface = \"bold\", color = \"gray30\"),\n    axis.title.y = element_text(size = 9, fontface = \"bold\", color = \"gray30\"),\n    axis.text.x = element_text(size = 8.5),\n    axis.text.y = element_text(size = 9, fontface = \"bold\"),\n    plot.title = element_text(size = 12, fontface = \"bold\"),\n    plot.subtitle = element_text(size = 9, color = \"gray40\")\n  )\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nThis bar chart compares the **Portfolio Loss Ratio** across different insurance policy types. In insurance, the **Loss Ratio** ($\\text{Sum of Incurred Losses} / \\text{Sum of Premiums}$) measures profitability.\n\n-   **COMP_N (93.9%)**: This product has the **highest loss ratio**. For every \\$100 collected in premiums, \\$93.90 goes directly toward paying claims.\n\n-   **COMP_E (73.8%) & TPG (69.2%)**: These two lines fall into a moderate risk zone, hovering around the 70% mark.\n\n-   **CC (63.4%)**: Shows a solid, healthy underwriting performance.\n\n-   **TP (54.3%)**: This product has the **lowest loss ratio**, meaning it is the most profitable line in the portfolio. Only \\$54.30 out of every \\$100 collected is used to cover claims.\n\nNext a non-parametric Kruskal-Wallis ANOVA is executed to determine whether underwriting profitability profiles vary systematically across product types.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npolicy_association_data <- insurance_processed %>%\n  filter(total_premium > 0 & !is.na(policy_type)) %>% \n  mutate(\n    loss_ratio = total_incurred / total_premium,\n    profitability_tiers = case_when(\n      loss_ratio == 0                   ~ \"0% (No Loss)\",\n      loss_ratio > 0 & loss_ratio <= 1  ~ \"0%-100% (Profitable)\",\n      loss_ratio > 1                    ~ \">100% (Loss-making)\"\n    )\n  )\n\npolicy_association_data$policy_type <- as.factor(policy_association_data$policy_type)\npolicy_association_data$profitability_tiers <- fct_relevel(\n  policy_association_data$profitability_tiers, \n  \"0% (No Loss)\", \"0%-100% (Profitable)\", \">100% (Loss-making)\"\n)\n\n\nggbarstats(\n  data = policy_association_data,      \n  x = profitability_tiers,      \n  y = policy_type,              \n  bf.message = FALSE,           \n  labels.size = 2.8,            \n  title = \"Significant Test of Association: Underwriting Profitability Tiers vs. Policy Types\",\n  xlab = \"Insurance Policy Types\",\n  legend.title = \"Loss Ratio Brackets\",\n  package = \"ggthemes\",\n  palette = \"Purple_Pink\"\n)\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-27-1.png){width=1344}\n:::\n:::\n\n\nThe above chart divides policies into three distinct financial performance tiers:\n\n-   **0% (No Loss)**: Policies that generated premium revenue but filed zero claims. This is the largest segment for all products, ranging from **71% to 95%**.\n\n-   **0%-100% (Profitable )**: Policies that had claims, but the claim cost was less than the premium paid (profitable individual contracts). This represents a small sliver (**1% to 8%**).\n\n-   **\\>100% (Loss)**: Policies where the claim cost exceeded the premium paid (contracts that lost money).\n\nThe results show that product type has a real impact on portfolio performance. Although the relationship is not extremely strong, it is statistically meaningful and financially relevant.\n\nAmong all products, COMP_N stands out as the weakest performer. Around 21% of its policies have loss ratios above 100%, meaning these policies are generating underwriting losses. At the same time, COMP_N also has the lowest proportion of claim-free policies, which explains its high overall loss ratio.TP performs much better, with about 95% of policies remaining claim-free. This makes it the most stable and profitable product in the portfolio.\n\n## 4.5 Key Underwriting Drivers: Claim Frequency vs. Claim Severity\n\nThis step is to decompose the underlying financial risk drivers of each policy types by breaking down overall profitability into its two foundational actuarial components: Claim Frequency (claims per policy) and Average Claim Severity (cost per incurred claim).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntwin_axis_data <- insurance_processed %>%\n  filter(total_premium > 0 & !is.na(policy_type)) %>%\n  group_by(policy_type) %>%\n  summarize(\n    total_policies = n(),\n    grand_claims   = sum(total_claims, na.rm = TRUE),\n    grand_incurred = sum(total_incurred, na.rm = TRUE),\n    # Actuarial Metric Derivations\n    claim_frequency  = grand_claims / total_policies,\n    average_severity = if_else(grand_claims > 0, grand_incurred / grand_claims, 0),\n    .groups = \"drop\"\n  )\n\nscale_factor <- max(twin_axis_data$average_severity) / max(twin_axis_data$claim_frequency)\n\n\nggplot(data = twin_axis_data, aes(x = policy_type)) +\n  geom_bar(aes(y = average_severity, fill = average_severity), stat = \"identity\", width = 0.5, alpha = 0.75, show.legend = FALSE) +\n  geom_text(aes(y = average_severity, label = paste0(\"$\", round(average_severity, 0))), vjust = -0.4, size = 3, fontface = \"bold\") +\n  geom_line(aes(y = claim_frequency * scale_factor, group = 1), color = \"#e91e63\", size = 1.2) +\n  geom_point(aes(y = claim_frequency * scale_factor), color = \"#c2185b\", size = 2.5) +\n  geom_text(aes(y = claim_frequency * scale_factor, label = scales::percent(claim_frequency, accuracy = 0.1)), vjust = -0.8, color = \"#c2185b\", fontface = \"bold\", size = 3) +\n  scale_y_continuous(\n    name = \"Average Claim Severity\",\n    labels = scales::dollar,\n    sec.axis = sec_axis(~ . / scale_factor, name = \"Claim Frequency per Policy (%)\", labels = scales::percent)\n  ) +\n  scale_fill_gradient(low = \"#b39ddb\", high = \"#4a148c\") +\n  labs(\n    title = \"Claim Frequency vs. Average Severity Matrix\",\n    subtitle = \"Bars represent Average Severity (Left Y) | Pink Line represents Claim Frequency (Right Y) across all policy types\",\n    x = \"Policy Types\"\n  ) +\n  theme_minimal() +\n  theme(\n    panel.grid.major.x = element_blank(),\n    axis.title.y = element_text(color = \"#4a148c\", fontface = \"bold\", size = 9),\n    axis.title.y.right = element_text(color = \"#c2185b\", fontface = \"bold\", size = 9),\n    axis.text.x = element_text(fontface = \"bold\", size = 9)\n  )\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-28-1.png){width=1344}\n:::\n:::\n\n\nFrom this chart we can see the root cause of the loss.\n\n-   **COMP_N is a \"High-Frequency\" issue, not a \"High-Cost\" one**: Its average claim cost is the lowest (**\\$752**), but its claim frequency is an astronomical **79.8%**. The product is losing money because it is flooded with high-risk drivers making frequent minor claims.\n\n-   **TP's profit is driven by an exceptionally low claim rate**: Although TP has a high cost per claim (**\\$1,092**), only **8.8%** of policies ever file a claim. This extremely low frequency easily offsets the high severity, making it the most profitable product.\n\n-   **Clear strategic action plan**: For COMP_N, management should **increase deductibles** to eliminate small claims rather than trying to lower repair costs. For TP, the current underwriting guidelines are highly effective and should be maintained.\n\n## 4.6 Multi-Year Portfolio Loss Ratio Trends\n\nThis step is to evaluate the temporal sustainability and margin stability of each policy types across multiple consecutive underwriting years.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrend_data <- insurance_processed %>%\n  filter(total_premium > 0 & !is.na(policy_type) & !is.na(year)) %>%\n  group_by(year, policy_type) %>%\n  summarize(\n    yearly_incurred = sum(total_incurred, na.rm = TRUE),\n    yearly_premium  = sum(total_premium, na.rm = TRUE),\n    loss_ratio      = yearly_incurred / yearly_premium,\n    .groups = \"drop\"\n  )\n\n\nggplot(data = trend_data, aes(x = policy_type, y = loss_ratio, fill = as.factor(year))) +\n  geom_bar(stat = \"identity\", position = position_dodge(width = 0.7), width = 0.6) +\n  geom_text(aes(label = scales::percent(loss_ratio, accuracy = 1)), \n            position = position_dodge(width = 0.7), vjust = -0.4, size = 2.5, fontface = \"bold\") +\n\n  geom_hline(yintercept = 1.0, linetype = \"dashed\", color = \"red\", alpha = 0.5) +\n  scale_fill_manual(values = c(\"2022\" = \"#e1bee7\", \"2023\" = \"#ba68c8\", \"2024\" = \"#7b1fa2\"), name = \"Year\") +\n  scale_y_continuous(labels = scales::percent, expand = expansion(mult = c(0, 0.15))) +\n  labs(\n    title = \"Loss Ratio across Years by Policy Types\",\n    x = \"Policy Types\",\n    y = \"Portfolio Loss Ratio (%)\"\n  ) +\n  theme_minimal() +\n  theme(\n    panel.grid.major.x = element_blank(),\n    legend.position = \"top\",\n    axis.title.x = element_text(size = 9, fontface = \"bold\", color = \"gray30\"),\n    axis.title.y = element_text(size = 9, fontface = \"bold\", color = \"gray30\"),\n    axis.text.x = element_text(fontface = \"bold\", size = 9)\n  )\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-29-1.png){width=1344}\n:::\n:::\n\n\nThis chart displays the multi-year trend of the **Portfolio Loss Ratio** across different policy types from 2022 to 2024. The red dashed line highlights the **100% threshold**, above which a product becomes completely unprofitable.\n\n-   **COMP_N has officially crossed into a deficit**: Its loss ratio has deteriorated aggressively year-over-year, climbing from **73%** in 2022 to **92%** in 2023, and peaking at **102%** in 2024. At 102%, COMP_N is losing money on claims alone, even before accounting for operational expenses.\n\n-   **Widespread margin erosion across the portfolio**: Except for CC (which stabilized at **66%**), every other product line shows a clear upward trend in loss ratios. Most notably, **TP** more than doubled its ratio from **30%** to **64%**, and **COMP_E** rose steadily from **66%** to **79%**.\n\n-   **The portfolio-wide problem confirmed**: This chart confirms that the overall portfolio deterioration we noted earlier (the rapid rise in total incurred claims outpacing premium growth) is not an isolated issue. While COMP_N is the most critical threat, the shrinking profit margins across almost all segments suggest a systemic underpricing of risk or an increase in claims frequency over the last three years.\n\n# 5. Portfolio Risk Stratification\n\nThis step is to aggregate continuous commercial premium volumes and cumulative claim counts across overlapping multi-dimensional risk facets simultaneously (Seating Capacity Groups intersected with Vehicle Age Cohorts).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(GGally)\n\nbox_pure_data <- insurance_processed %>%\n\n  filter(!is.na(policy_type) & !is.na(driver_age) & !is.na(vehicle_age) & \n         total_premium > 0) %>%\n  mutate(\n    loss_ratio   = total_incurred / total_premium,\n    log_premium  = log10(total_premium),\n    log_incurred = log10(total_incurred + 1)\n  ) %>%\n  filter(loss_ratio <= 5.0) %>%\n  select(policy_type, driver_age, vehicle_age, log_premium, log_incurred, loss_ratio) %>%\n  mutate(across(c(driver_age, vehicle_age, log_premium, log_incurred, loss_ratio), \n                ~ ( . - min(., na.rm = TRUE) ) / ( max(., na.rm = TRUE) - min(., na.rm = TRUE) ))) %>%\n  pivot_longer(\n    cols = -policy_type,\n    names_to = \"Dimension\",\n    values_to = \"Normalized_Value\"\n  ) %>%\n  mutate(\n    Dimension = case_when(\n      Dimension == \"driver_age\"   ~ \"Driver Age\",\n      Dimension == \"vehicle_age\"  ~ \"Vehicle Age\",\n      Dimension == \"log_premium\"  ~ \"Premium (Log)\",\n      Dimension == \"log_incurred\" ~ \"Incurred Loss (Log)\",\n      Dimension == \"loss_ratio\"   ~ \"Loss Ratio\",\n      TRUE ~ Dimension\n    ),\n    Dimension = fct_relevel(Dimension, \"Driver Age\", \"Vehicle Age\", \"Premium (Log)\", \"Incurred Loss (Log)\", \"Loss Ratio\")\n  )\n\nggplot(data = box_pure_data, aes(x = Dimension, y = Normalized_Value, fill = policy_type)) +\n  geom_boxplot(color = \"#4a148c\", width = 0.4, alpha = 0.85, outlier.alpha = 0.1, outlier.size = 1, show.legend = FALSE) +\n  facet_wrap(~ policy_type, ncol = 3) +\n  labs(\n    title = \"Multi-Dimensional Portfolio Boxplot Matrix\",\n    x = \"Actuarial & Operational Dimensions\",\n    y = \"Standardized Value Scale [0.00 - 1.00]\"\n  ) +\n  theme_minimal() +\n  theme(\n    panel.grid.major.x = element_line(color = \"gray90\", size = 0.4), \n    strip.background = element_rect(fill = \"#4a148c\"),               \n    strip.text = element_text(color = \"white\", fontface = \"bold\", size = 9),\n    axis.title.x = element_text(size = 9, fontface = \"bold\", color = \"gray30\"),\n    axis.title.y = element_text(size = 9, fontface = \"bold\", color = \"gray30\"),\n    axis.text.x = element_text(angle = 20, hjust = 1, size = 8, fontface = \"bold\"), \n    axis.text.y = element_text(size = 8),\n    plot.title = element_text(size = 11, fontface = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](Technical_Report_files/figure-html/unnamed-chunk-30-1.png){width=1344}\n:::\n:::\n\n\nThe above boxplot shows a multi-dimensional view of risk across five policy types. All variables（Driver Age, Vehicle Age, Premium, Incurred Loss, and Loss Ratio）have been rescaled to a 0 to 1 range so they can be compared more easily.\n\n-   First, the demographic variables (Driver Age and Vehicle Age) look almost identical across all five products. The median, spread, and overall shape are very similar, which suggests there is no real customer segmentation between product types.\n\n-   Second, COMP_N stands out in terms of pricing and claims. Its premiums are generally higher than most other products, but it also shows much larger incurred losses, with a wide spread.\n\n-   Finally, the loss ratio patterns are highly skewed. For most products (CC, COMP_E, TP, and TPG), the boxplots sit close to zero, with occasional extreme values appearing as outliers. This indicates that most policies are claim-free, while a small number of cases drive the losses. COMP_N, however, shows a slightly higher baseline, suggesting more frequent or consistent losses compared to the others.\n\n# 6. Strategic Conclusions & Actionable Recommendations\n\n## 6.1 Core Actuarial Findings\n\nThe analysis of the automobile insurance portfolio (2022–2024) shows that the company’s poor profitability is mainly caused by several high-risk segments rather than the whole portfolio.\n\n**First, `COMP_N` shows clear pricing issues.** It recorded a **102% loss ratio in 2024**, which is well above the break-even level. The main driver is not high claim severity, but extremely high claim frequency at **79.8%**, combined with relatively small claim amounts. This indicates that a large number of policyholders are making frequent minor claims, which steadily erodes profitability.\n\n**Second, older vehicles in New Business are significantly riskier.** For vehicles older than 10 years, New Business policies show much higher loss ratios compared to renewal business. This suggests potential adverse selection, where higher-risk customers are more likely to enter the portfolio through older vehicles.\n\n**Finally, exposure is heavily concentrated in older vehicles.** A large share of the portfolio consists of 5-seater vehicles aged between 10 and 40 years. As a result, these older-vehicle segments have a disproportionate impact on overall profitability.\n\n## 6.2 Target Underwriting Action Plan\n\nTo address these issues, we recommend the following actions:\n\n**First, increase deductibles for `COMP_N`.** This helps reduce frequent small claims and improves overall loss experience.\n\n**Second, tighten underwriting for older vehicles in New Business.** For vehicles older than 10 years, additional claims-history checks should be introduced, while also prioritising the retention of existing renewal customers.\n\n**Third, adjust pricing for older vehicles.** Premiums for vehicles above 15 years old should be increased to better reflect their higher underlying risk.\n",
    "supporting": [
      "Technical_Report_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}